Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -31,10 +31,11 @@ jobs:
 
       - name: Debug build output
         run: |
-            ls
-            ls build
-            ls build/libs
-
+          echo "PWD:"; pwd
+          echo "Root contents:"; ls
+          echo "build:"; ls build || echo "build missing"
+          echo "build/libs:"; ls build/libs || echo "build/libs missing"
+          
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
